enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/logo-fakultas-vokasi.png:
    name: logo-fakultas-vokasi.png
    full_path: logo-fakultas-vokasi.png
    type: image/png
    size: 8257
    path: user/themes/quark/images/logo/logo-fakultas-vokasi.png
custom_logo_mobile:
  user/themes/quark/images/logo/Logo-Branding-UNAIR-biru.png:
    name: Logo-Branding-UNAIR-biru.png
    full_path: Logo-Branding-UNAIR-biru.png
    type: image/png
    size: 246403
    path: user/themes/quark/images/logo/Logo-Branding-UNAIR-biru.png
